const LABELS: Record<string, string> = {
  mate: 'Matt',
  mateIn1: 'Matt in 1',
  mateIn2: 'Matt in 2',
  mateIn3: 'Matt in 3',
  mateIn4: 'Matt in 4',
  mateIn5: 'Matt in 5',
  backRankMate: 'Grundreihenmatt',
  scholarsMate: 'Schäfermatt',
  ladderMate: 'Leitermatt',
  smotheredMate: 'Ersticktes Matt',
  arabianMate: 'Arabisches Matt',
  anastasiaMate: 'Anastasias Matt',
  bodenMate: 'Bodens Matt',
  doubleBishopMate: 'Doppelläufer-Matt',
  dovetailMate: 'Schwalbenschwanz-Matt',
  hookMate: 'Haken-Matt',
  fork: 'Gabel',
  pin: 'Fesselung',
  skewer: 'Spieß',
  discoveredAttack: 'Abzugsangriff',
  doubleCheck: 'Doppelschach',
  xRayAttack: 'Röntgenangriff',
  attraction: 'Ablenkung auf ein Feld',
  deflection: 'Ablenkung',
  clearance: 'Linienräumung',
  interference: 'Unterbrechung',
  intermezzo: 'Zwischenzug',
  sacrifice: 'Opfer',
  quietMove: 'Stiller Zug',
  defensiveMove: 'Verteidigung',
  trappedPiece: 'Gefangene Figur',
  hangingPiece: 'Ungedeckte Figur',
  capturingDefender: 'Verteidiger schlagen',
  exposedKing: 'Ungeschützter König',
  kingsideAttack: 'Angriff am Königsflügel',
  queensideAttack: 'Angriff am Damenflügel',
  advancedPawn: 'Weit vorgerückter Bauer',
  promotion: 'Umwandlung',
  underPromotion: 'Unterverwandlung',
  castling: 'Rochade',
  enPassant: 'En passant',
  zugzwang: 'Zugzwang',
  bishop: 'Läufer',
  rook: 'Turm',
  queen: 'Dame',
  knight: 'Springer',
  pawnEndgame: 'Bauernendspiel',
  rookEndgame: 'Turmendspiel',
  bishopEndgame: 'Läuferendspiel',
  knightEndgame: 'Springerendspiel',
  queenEndgame: 'Damenendspiel',
  queenRookEndgame: 'Dame-und-Turm-Endspiel',
  opening: 'Eröffnung',
  middlegame: 'Mittelspiel',
  endgame: 'Endspiel',
  short: 'Kurze Aufgabe',
  long: 'Lange Aufgabe',
  veryLong: 'Sehr lange Aufgabe',
  oneMove: 'Ein Zug',
  advantage: 'Vorteil gewinnen',
  crushing: 'Entscheidender Vorteil',
  equality: 'Ausgleich',
  master: 'Aus Meisterpartie',
  masterVsMaster: 'Aus Meisterduell',
  superGM: 'Aus Großmeisterpartie',
};

const META = new Set([
  'mate',
  'short',
  'long',
  'veryLong',
  'oneMove',
  'advantage',
  'crushing',
  'equality',
  'master',
  'masterVsMaster',
  'superGM',
  'opening',
  'middlegame',
  'endgame',
]);

export function themeLabel(theme: string): string {
  return LABELS[theme] ?? theme;
}

export function isMetaTheme(theme: string): boolean {
  return META.has(theme);
}
